### ISSUE TITLE
alek is a gaffot

### ISSUE THREAD

**Issue by sovietspaceship** [telegram-wired/infornography-sh#1]
What steps will reproduce the problem?
1. talk to alek
2. see he's a gaffot

What is the expected output? What do you see instead?
Expected non-gaffot. Saw a gaffot.

What version of the product are you using? On what operating system?
0.6.66 on Plan9

Please provide any additional information below.
alec is a gatof

**Comment by jakuzure** [comment]
try posting "alek fagotto" stickers

**Comment by u7knv9h** [comment]
it'll be fixed in the next commit

**Comment by sovietspaceship** [comment]
Thank you that solved the issue.
